fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    eyplib: "git://github.com/SaltaIT/eyp-eyplib.git"
    systemd: "git://github.com/SaltaIT/eyp-systemd.git"
    epel: "git://github.com/jordiprats/eyp-epel.git"
  symlinks:
    redis: "#{source_dir}"
